Shop\Basket\Basket:
  properties:
    id:
      type: Shop\Basket\Id
    products:
      exclude: true
      expose: false
    ownerEmail:
      type: string
    open:
      exclude: true
      expose: false